version: "3"
services:
  expo:
    image: khadamaty-mobile-app
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
    command: ["npx", "expo", "start", "--tunnel"]
